### PR TITLE
ENH: Update extension metadata

### PR DESCRIPTION
**Pull request by jcfr**
Consolidate extension metadata based on the corresponding s4ext file organized
in the ExtensionsIndex repository.

### CODE REVIEW

**Comment by jcfr** [comment]
Please, could this be reviewed & merged :pray:

**Comment by jcfr** [comment]
Email sent on July 3rd 2024 to @hina-shah with @lassoan in cc:

```
Subject: Help to merge https://github.com/hina-shah/SlicerBatchAnonymize/pull/21

Hi Hina,

When you have chance, we would appreciate your help to merge the following pull request:

  ENH: Update extension metadata
  https://github.com/hina-shah/SlicerBatchAnonymize/pull/21
  
Changes are trivial as they only include updates to the extension metadata.

Thanks
J-Christophe
```

**Comment by hina-shah** [comment]
Absolutely! Sorry for being so late in doing this.

**Comment by lassoan** [comment]
To relieve you from responsibilities in the future, you could consider moving this repository to the `Slicer` organization. You can do it in the repository settings by a few clicks.

**Comment by jcfr** [comment]
@hina-shah  Thanks for taking the time to follow-up :pray: :rocket:

**Pull request merged**
